---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protected-site
  labels:
    app: protected-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protected-site
  template:
    metadata:
      labels:
        app: protected-site
    spec:
      containers:
      - name: app
        image: nginx
        ports:
        - containerPort: 80
      - name: jwt-proxy
        image: myregistry.url/i/jwt-proxy
        env:
        - name: JWT_PROXY_UPSTREAM
          value: http://localhost:80/
        - name: JWT_PROXY_CLIENT_ID
          value: <your-azureclient-id>
        - name: JWT_PROXY_ISSUER_URI
          value: https://sts.windows.net/<tenant-id>/
        - name: JWT_PROXY_KEYSET_URI
          value: https://login.microsoftonline.com/<tenant-id>/discovery/v2.0/keys
        ports:
        - containerPort: 8484
---
apiVersion: v1
kind: Service
metadata:
  name: protected-site
spec:
  selector:
    app: protected-site
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8484
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: protected-site
spec:
  rules:
  - host: mywebsite.url
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: protected-site
            port:
              number: 80
